### ISSUE TITLE
Firefox display issue

### ISSUE THREAD

**Issue by nofurtherinformation** [civic-data-design-lab/venice-collectives#36]
![image](https://user-images.githubusercontent.com/10041771/82365575-d4c9b600-99de-11ea-9a3f-f55ae8bd251c.png)

**Comment by kafleprabhakar** [comment]
This is a really weird behavior. I made a small change, which technically shouldn't have made any difference, but seems to solve the issue. The transition animation is still kind of weird though.

**Comment by nofurtherinformation** [comment]
Yeah -- super weird one, especially because after you interact with it, it fixes. Seemed to be something Firefox didn't like about `position:sticky`?

**Comment by kafleprabhakar** [comment]
Yeah, `position:sticky` doesn't always seem to work properly when it is a child of a flexbox in Firefox.
