### ISSUE TITLE
Add link to website if in data

### ISSUE THREAD

**Issue by cotequotey** [civic-data-design-lab/venice-collectives#6]
![website](https://user-images.githubusercontent.com/19614284/79170312-ff5f9800-7dbc-11ea-88dd-ce48734a41e8.png)
As shown here, the website link is next to the title ( in both the popup and the initial card) so we are moving it to be a link for the title instead. Change hyperlink color to red: #ff0000

**Comment by kafleprabhakar** [comment]
Was just some javascript issue
